Agregar dependencia de coreutils y verificar instalación de shred en el script postinst

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,3 +1,16 @@
 #!/bin/bash
+
 set -e
+
+# Check if shred is installed
+if ! command -v shred &> /dev/null
+then
+    echo "shred could not be found. Installing coreutils..."
+    sudo apt-get update
+    sudo apt-get install -y coreutils
+fi
+
 echo "Instalation successful."
+exit 0
+
+
